# Site settings
title: Chris & Nikita
email: chris@baclig.me
url: https://example.github.io
description: "Chris & Nikita"
baseurl: ""

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Chris & Nikita

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

story:
  - year: 2006
    title: Chris and Nikita First Meet
    image: meet.jpg
    content: TODO
  - year: 2007
    title: Chris and Nikita Start Dating
    image: date.jpg
    content: TODO
  - year: 2007
    title: Nikita Goes to Greece
    image: greece.jpg
    content: TODO
  - year: 2007-2009
    title: Chris and Nikita Fall in Love at Stanford
    image: stanford.jpg
    content: TODO
  - year: 2009
    title: Chris and Nikita Graduate from Stanford
    image: graduate.jpg
    content: TODO
  - year: 2011
    title: Nikita Moves to Chicago
    image: nikita-to-chicago.jpg
    content: TODO
  - year: 2013
    title: Chris Moves to Chicago
    image: chris-to-chicago.jpg
    content: TODO
  - year: 2014
    title: Chris Pops the Question
    image: engagement.jpg
    content: TODO

# Build settings
markdown: kramdown
permalink: pretty

google:
  key: AIzaSyB6rRW9hmltJZvoNLO7dewTmGqZn8LIRFU
